import React from 'react';
import { usePipelineStore, ProjectHistoryItem } from '../store/pipelineStore';
import { History, Clock, FileCode, CheckCircle2, ArrowRight } from 'lucide-react';

export const HistoryPanel: React.FC = () => {
  const { history, loadHistoryItem } = usePipelineStore();

  if (history.length === 0) {
    return (
      <div className="h-full bg-slate-950 p-6 flex flex-col items-center justify-center text-center text-slate-500">
        <History className="w-10 h-10 text-slate-700 mb-2" />
        <p className="text-xs font-semibold text-slate-400">No Generation History Yet</p>
        <p className="text-[11px] text-slate-600 mt-1 max-w-xs">
          Projects generated by CodeForge V2 will automatically be stored here for instant restoration and inspection.
        </p>
      </div>
    );
  }

  return (
    <div className="h-full bg-slate-950 p-4 text-slate-200 overflow-y-auto space-y-3">
      <div className="flex items-center gap-2 border-b border-slate-800 pb-2 text-xs font-bold text-slate-300 uppercase tracking-wider">
        <History className="w-4 h-4 text-indigo-400" />
        Project Build History ({history.length})
      </div>

      <div className="space-y-2.5">
        {history.map((item) => (
          <div
            key={item.id}
            onClick={() => loadHistoryItem(item)}
            className="p-3.5 bg-slate-900 border border-slate-800 hover:border-indigo-600/80 rounded-xl cursor-pointer transition-all hover:shadow-lg group text-xs space-y-2"
          >
            <div className="flex items-center justify-between text-slate-400 text-[10px]">
              <span className="flex items-center gap-1 font-mono">
                <Clock className="w-3 h-3 text-slate-500" /> {item.timestamp}
              </span>
              {item.reviewResult && (
                <span className="px-2 py-0.5 bg-emerald-950 text-emerald-400 border border-emerald-800 rounded font-bold font-mono">
                  Grade {item.reviewResult.overallGrade} ({item.reviewResult.overallScore}/100)
                </span>
              )}
            </div>

            <div className="font-semibold text-slate-100 group-hover:text-indigo-300 transition-colors line-clamp-2">
              &quot;{item.prompt}&quot;
            </div>

            <div className="flex items-center justify-between text-[11px] text-slate-400 pt-1 border-t border-slate-800/80">
              <span className="flex items-center gap-1 font-mono">
                <FileCode className="w-3.5 h-3.5 text-indigo-400" />
                {item.fileTree.length} Files Generated
              </span>
              <span className="text-indigo-400 font-medium flex items-center gap-1 group-hover:translate-x-1 transition-transform">
                Load Workspace <ArrowRight className="w-3 h-3" />
              </span>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};
